# CI/CD pipeline builds the Docker image and pushes it to the GitHub Container Registry
# Then it runs the Sphinx documentation build and deploys it to GitHub Pages
# Finally it tests the FastMIMIC3 package
# -- DEBUG --
# Trigger: git commit --allow-empty -m "Trigger pipeline" && git push

name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  test-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for cached image
        id: check-image-cache
        run: |
          if [ -f ~/image-cache/fastmimic3.tar ]; then
            echo "cache-hit=true" >> $GITHUB_OUTPUT
          else
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

      - name: Load cached image
        if: steps.check-image-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i ~/image-cache/fastmimic3.tar
          echo "Loaded cached image"

      - name: Build Docker image
        run: |
          docker build -t amadou1998/fastmimic3:latest -t amadou1998/fastmimic3:${{ github.sha }} -f .devcontainer/Dockerfile.ci .


      - name: Save image to cache
        if: steps.check-image-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/image-cache
          docker save -o ~/image-cache/fastmimic3.tar amadou1998/fastmimic3:latest
          echo "Saved new image to cache"

      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          docker push amadou1998/fastmimic3:latest
          docker push amadou1998/fastmimic3:${{ github.sha }}

      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: "amadou1998/fastmimic3:${{ github.sha }}"
          fail-build: false
          severity-cutoff: high
  docs:
    runs-on: self-hosted
    needs: test-and-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true