# CI/CD pipeline builds the Docker image and pushes it to the GitHub Container Registry
# Then it runs the Sphinx documentation build and deploys it to GitHub Pages
# Finally it tests the pymimic3 package
# -- DEBUG --
# Trigger: >git commit --allow-empty -m "Trigger pipeline" && git push

name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

env:
  DOCKER_VOLUME_MOUNTS: >-
    -v $DOCKER_CACHE_DIR/.github-action-cache/control-dataset:/workdir/tests/data/control-dataset
    -v $DOCKER_CACHE_DIR/.github-action-cache/mimiciii-demo:/workdir/tests/data/mimiciii-demo
    -v $DOCKER_CACHE_DIR/.github-action-cache/semitemp:/workdir/tests/data/semitemp
    -v $DOCKER_CACHE_DIR/.github-action-cache/bash-results:/workdir/tests/data/bash-results
    -v $DOCKER_CACHE_DIR/.github-action-cache/pytest-results:/workdir/tests/data/pytest-results

jobs:
  build-and-push:
    # |-> 1. pull code
    # |-> 2. set up docker buildx 
    # |-> 3. login to docker hub
    # |-> 4. setup cache dir
    # |      - ?=self-hosted
    # |-> 5. extract branch name
    # |-> 6. setup cache on runner machine
    # |      - ?=self-hosted|github-hosted
    # |-> 7. build and export docker image
    # |      - ?=self-hosted|github-hosted
    # |-> 8. push the image
    # |-> 9. move cache
    # '-> 10. scan image for vulnerabilities
    runs-on: self-hosted # -> ubuntu-latest to run in github cloud
    steps:
      # => 1. Pull code into runner env
      - name: Checkout code
        uses: actions/checkout@v4

      # => 2. Set up Docker Buildx step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # => 3. Login to docker hub to push images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Secrets stored in repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # => 4. Create cache directory if runing locally
      - name: Set up Docker cache/output directory on self-hosted
        if: runner.environment == 'self-hosted'
        run: |
          echo cache dir is: ${{ env.DOCKER_CACHE_DIR }}
          if [ -n "$DOCKER_CACHE_DIR" ]; then
            echo "Using runner's DOCKER_CACHE_DIR: $DOCKER_CACHE_DIR"
          else
            DOCKER_CACHE_DIR="/tmp"
            echo "DOCKER_CACHE_DIR not set on runner. Using default: $DOCKER_CACHE_DIR"
          fi
          echo "DOCKER_CACHE_DIR=$DOCKER_CACHE_DIR" >> $GITHUB_ENV
          mkdir -p $DOCKER_CACHE_DIR
          mkdir -p $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/
          echo "Volume mounts for docker are: $DOCKER_VOLUME_MOUNTS"
          echo "Volume mounts for docker are: ${{ env.DOCKER_VOLUME_MOUNTS }}"


      # => 5. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      # => 6. Setup cache on runner machine: self-hosted
      - name: Cache Docker layers on self-hosted
        if: runner.environment == 'self-hosted'
        uses: maxnowack/local-cache@v2
        with: 
          path: ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-   
      
      # => 6. Setup cache on github cache: github hosted
      - name: Cache Docker layers on github-hosted
        if: runner.environment == 'github-hosted'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # => 7. Build and push Docker image: self-hosted (part 1) 
      - name: Build and export Docker image on self-hosted
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.ci
          push: false
          tags: |
            tensorpod/pymimic3:latest
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}
          cache-from: type=local,src=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
          cache-to: type=local,dest=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache-new,mode=max
          outputs: type=docker,dest=${{ env.DOCKER_CACHE_DIR }}/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar

      # => 7. Build and push Docker image: github hosted
      - name: Build and export Docker image on github-hosted
        if: runner.environment == 'github-hosted'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.ci
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tensorpod/pymimic3:latest
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar

      - name: Upload artifact
        if: runner.environment == 'github-hosted'
        uses: actions/upload-artifact@v4
        with:
          name: pymimic3.${{ steps.extract_branch.outputs.branch }}
          path: /tmp/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar

      # => 8. Push Docker image
      - name: Push Docker image
        if: github.event_name != 'pull_request' && runner.environment == 'self-hosted'
        run: |
          docker push tensorpod/pymimic3:latest
          docker push tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}

      # => 9. Move the cache with -new suffix to original cache
      - name: Move cache
        run: |
          if [ "${{ runner.environment }}" = "self-hosted" ]; then
            rm -rf ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
            mv ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache-new ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
          elif [ "${{ runner.environment }}" = "github-hosted" ]; then
            rm -rf tmp/.buildx-cache
            mv tmp/.buildx-cache-new tmp/.buildx-cache
          fi

      # => 10. Scan image for vulnerabilities
      # - name: Scan image for vulnerabilities
      #   uses: anchore/scan-action@v3
      #   with:
      #     image: "tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}"
      #     fail-build: false
      #     severity-cutoff: high
 # # Documentation build and deploy
 # docs:
 #   runs-on: self-hosted
 #   needs: build-and-push
 #   steps:
 #     - uses: actions/checkout@v4
 #     - uses: actions/setup-python@v5
 #     - name: Install dependencies
 #       run: |
 #         pip install sphinx sphinx_rtd_theme myst_parser
 #     - name: Sphinx build
 #       run: |
 #         sphinx-build doc _build
 #     - name: Deploy to GitHub Pages
 #       uses: peaceiris/actions-gh-pages@v3
 #       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
 #       with:
 #         publish_branch: gh-pages
 #         github_token: ${{ secrets.GITHUB_TOKEN }}
 #         publish_dir: _build/
 #         force_orphan: true
#
# Pytest run test
  setup-control-dataset:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup persistent test mounts
        shell: bash
        run: |
          mkdir -p $DOCKER_CACHE_DIR/.github-action-cache/{pytest-results,bash-results}

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Setup control dataset
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
            bash -c "cd etc && make testing=true >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1 "
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi

  setup-fixtures:
    needs: setup-control-dataset
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run fixture setup tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
            bash -ic "pytest --no-cleanup -v tests/testz_setup_all_fixtures.pymimic3 
            >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1"
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


  test-pytest-suite:
    needs: setup-fixtures
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run pytest suite tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
          bash -ic "pytest --no-cleanup -v tests/test_pytest_suite.py \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1"
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


  test-datasets:
    needs: test-pytest-suite
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run dataset tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
          bash -ic "pytest --no-cleanup -v tests/test_datasets \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1"
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


  test-preprocessing:
    needs: test-pytest-suite
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run preprocessing tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
          bash -ic "pytest --no-cleanup -v tests/test_preprocessing \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1"
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


  test-metrics:
    needs: test-pytest-suite
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run metrics tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
          bash -ic "pytest --no-cleanup -v tests/test_metrics \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1"
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


  test-models:
    needs: [test-datasets, test-preprocessing, test-metrics]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # => xx. Extract branch name (may fail on pull requests, untested)
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Load cached image
        run: |
          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
          echo docker iamge ls -a

      - name: Run model tests
        run: |
          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
            pytest --no-cleanup -v tests/test_models \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi


      - name: Cleanup semitemp directory
        if: always()
        run: |
          rm -rf $DOCKER_CACHE_DIR/.github-action-cache/semitemp \
          >> /workdir/tests/data/bash-results/${GITHUB_SHA}.txt 2>&1
          echo "Exit status: $?"
          if [ $? -ne 0 ]; then
            echo "The command failed."
            exit 1
          fi