# CI/CD pipeline builds the Docker image and pushes it to the GitHub Container Registry
# Then it runs the Sphinx documentation build and deploys it to GitHub Pages
# Finally it tests the pymimic3 package
# -- DEBUG --
# Trigger: git commit --allow-empty -m "Trigger pipeline" && git push

name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  # Docker build and deploy
  test-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for cached image
        id: check-image-cache
        run: |
          if [ -f ~/image-cache/pymimic3.latest.tar ]; then
            echo "cache-hit-latest=true" >> $GITHUB_OUTPUT
          else
            echo "cache-hit-${{ github.sha }}=false" >> $GITHUB_OUTPUT
          fi

      - name: Load latest cached image
        if: steps.check-image-cache.outputs.cache-hit-latest == 'true'
        run: |
          docker load -i ~/image-cache/pymimic3.${{ github.sha }}.tar
          echo "Loaded cached image"

      - name: Load ${{ github.sha }} cached image
        if: steps.check-image-cache.outputs.cache-hit-${{ github.sha }} == 'true'
        run: |
          docker load -i ~/image-cache/pymimic3.${{ github.sha }}.tar
          echo "Loaded cached image"

      - name: Build Docker image
        run: |
          docker build -t tensor-works/pymimic3:latest -t tensor-works/pymimic3:${{ github.sha }} -f .devcontainer/Dockerfile.ci .


      - name: Save latest image to cache
        if: steps.check-image-cache.outputs.cache-hit-latest != 'true'
        run: |
          mkdir -p ~/image-cache
          docker save -o ~/image-cache/pymimic3.latest.tar tensor-works/pymimic3:latest
          echo "Saved new image to cache"

      - name: Save ${{ github.sha }} image to cache
        if: steps.check-image-cache.outputs.cache-hit-${{ github.sha }} != 'true'
        run: |
          mkdir -p ~/image-cache
          docker save -o ~/image-cache/pymimic3.${{ github.sha }}.tar tensor-works/pymimic3:${{ github.sha }}
          echo "Saved new image to cache"

      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          docker push tensor-works/pymimic3:latest
          docker push tensor-works/pymimic3:${{ github.sha }}

      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: "tensor-works/pymimic3:${{ github.sha }}"
          fail-build: false
          severity-cutoff: high

  # Documentation build and deploy
  docs:
    runs-on: self-hosted
    needs: test-and-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

  # Pytest run test
  pytest:
    runs-on: self-hosted
    needs: test-and-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load cached image
        run: |
          docker load -i ~/image-cache/pymimic3.tar
          echo "Loaded cached image for testing"

      - name: Test generators
        run: |
          docker run --rm tensor-works/pymimic3:latest pytest /workingdir/tests/test_generators.py

      - name: Upload pytest results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: pytest-results/